### ISSUE TITLE
Release a patch for allow header?

### ISSUE THREAD

**Issue by lenovouser** [x-v8/ngx_http_cors_filter#1]
Can you release a patch tag (Maybe `v0.2.1`?) for e80f12a1ba8df56288a39dc35c1c1b3318e115bc? I am pulling by tags only and would like to get that fix into the binary.

Cheers

**Comment by lenovouser** [comment]
@detailyang any updates?

**Comment by detailyang** [comment]
sorry, I just saw this:(. i will patch 0.2.1 as soon as possible

**Comment by detailyang** [comment]
@lenovouser I have released 0.2.1

**Comment by lenovouser** [comment]
@detailyang thank you very much! No problem 👍 Awesome work with the NGINX modules by the way!
